console.group("--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--")
console.log('Welcome to DeepInVue!')
console.groupEnd()
console.group("--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--")
console.groupEnd()